import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import LoginBtn from './Login/LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { LogOutBtn } from './Login/LogoutBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const loginSessionInfo = await getServerSession(authOptions);

  console.log(loginSessionInfo, "ㅇㅇ")

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar"> 
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link> 
          <Link href='/Login'>회원가입</Link>
          {loginSessionInfo ? (
            <>
              <h3>{loginSessionInfo.user.name}님 안녕하세요.</h3>
              <LogOutBtn />
            </>
          ) : (
            <LoginBtn />
          )}
          
        </div>
        {children}
      </body>
    </html>
  )
}
